# -*- coding: utf-8 -*-
"""simple code as he says

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EgRDzl3Z7C87b05zjuCUJYQX4IJg8j2X
"""

import streamlit as st 
st.title("BMI check")
mass=st.number_input("Enter ur  weight in kg", step=0.1)
height=st.number_input("Enter height in m", step=0.1)

button=st.button("Calculate BMI!")
if button:
  bmi=mass/(height)**2
  st.success(f"Your BMI is {bmi}")

